# docker-compose.yaml の設定

docker_settings:
  nginx:
    use: true
    parse_conf: false
  express:
    use: false
  python:
    use: false
  rust:
    use: true
  mysql:
    use: true
  php-apache:
    use: false
  php-fpm:
    use: false
  phpmyadmin:
    use: true
