networks:
  network:
    driver: bridge
services:
  mysql:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ndock_mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      TZ: Asia/Tokyo
    image: mysql:8
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 13306:3306
    volumes:
    - ../volumes/mysql/pool:/var/lib/mysql
    - ../volumes/mysql/conf.d:/etc/mysql/conf.d
    - ../volumes/mysql/sql:/docker-entrypoint-initdb.d
  nginx:
    container_name: ndock_nginx
    image: nginx:1.19
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 80:80
    volumes:
    - ../volumes/www:/var/www
    - ../volumes/logs/nginx:/var/log/nginx
    - ./images/nginx/main.conf:/etc/nginx/conf.d/default.conf
  phpmyadmin:
    container_name: ndock_phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=docker
    - PMA_PASSWORD=docker
    image: phpmyadmin/phpmyadmin
    networks:
    - network
    ports:
    - 8080:80
    volumes:
    - /sessions
  rust:
    build:
      args:
      - UID=$UID
      context: ./images/rust
    container_name: ndock_rust
    entrypoint: /entrypoint.sh
    networks:
    - network
    ports:
    - 8888:8888
    volumes:
    - ../volumes/home/rust:/code:rw
    - ./images/rust/entrypoint.sh:/entrypoint.sh
version: '3'
