networks:
  network:
    driver: bridge
services:
  express:
    build: ./images/express
    command:
    - sh
    - -c
    - yarn install && yarn build && yarn next:build && yarn next:start
    container_name: ndock_express
    image: node:14.15.1
    networks:
    - network
    ports:
    - 3000:3000
    volumes:
    - ../volumes/www/express:/home/node/express:rw
    working_dir: /home/node/express
  mysql:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ndock_mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      TZ: Asia/Tokyo
    image: mysql:8
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 3306:3306
    volumes:
    - ../volumes/mysql/pool:/var/lib/mysql
    - ../volumes/mysql/conf.d:/etc/mysql/conf.d
    - ../volumes/mysql/sql:/docker-entrypoint-initdb.d
  nginx:
    container_name: ndock_nginx
    image: nginx:1.19
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 80:80
    volumes:
    - ../volumes/www:/var/www
    - ../volumes/logs/nginx:/var/log/nginx
    - ./images/nginx/main.conf:/etc/nginx/conf.d/default.conf
  phpmyadmin:
    container_name: ndock_phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=docker
    - PMA_PASSWORD=docker
    image: phpmyadmin/phpmyadmin
    networks:
    - network
    ports:
    - 8080:80
    volumes:
    - /sessions
  python:
    build: ./images/python
    container_name: ndock_python
    entrypoint: /entrypoint.sh
    image: python:3
    networks:
    - network
    ports:
    - 8000:8000
    volumes:
    - ../volumes/home/django:/code:rw
    - ./images/python/entrypoint.sh:/entrypoint.sh
    working_dir: /code
version: '3'
