networks:
  network:
    driver: bridge
services:
  mysql:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ndock_mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      TZ: Asia/Tokyo
    image: mysql:5.7
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 3306:3306
    volumes:
    - ../volumes/mysql/pool:/var/lib/mysql
    - ../volumes/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ../volumes/mysql/sql:/docker-entrypoint-initdb.d
  nginx:
    container_name: ndock_nginx
    depends_on:
    - php-fpm
    image: nginx:1.19
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    ports:
    - 80:80
    volumes:
    - ../volumes/www:/var/www
    - ../volumes/logs/nginx:/var/log/nginx
    - ./images/nginx/main.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./images/php-fpm
    command: bash -c 'usermod -o -u ${UID} www-data; groupmod -o -g ${UID} www-data;
      php-fpm'
    container_name: ndock_php
    environment:
      TZ: Asia/Tokyo
    image: php:20201127
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 10m
    networks:
    - network
    volumes:
    - ./images/php/php.ini.main:/usr/local/etc/php/php.ini
    - ../volumes/www/:/var/www
    - ../volumes/logs/php-fpm:/var/log/php-fpm
  phpmyadmin:
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=docker
    - PMA_PASSWORD=docker
    image: phpmyadmin/phpmyadmin
    networks:
    - network
    ports:
    - 8080:80
    volumes:
    - /sessions
version: '3'
