version: "3"
networks:
  network:
    driver: bridge

services:
  php:
    container_name: php
    build: ./docker/images/php
    image: php:20201127
    volumes:
      - ./docker/images/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./volumes/www/:/var/www
      - ./volumes/logs/php-fpm:/var/log/php-fpm
    environment:
      TZ: Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - network

  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./volumes/www:/var/www
      - ./volumes/logs/nginx:/var/log/nginx
      - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - php
    networks:
      - network

  db:
    image: mysql:5.7
    container_name: db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/db/data:/var/lib/mysql
      - ./volumes/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./volumes/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - network
